### ISSUE TITLE
Availability in Windows Keyboard Layout

### ISSUE THREAD

**Issue by ElderDoge** [m2nlight/AHKShortcutLikeMac#1]
有没有一个简单的方法，将脚本中的Win键和Alt键互换，以实现使用Windows键盘布局模拟Mac键盘布局？

Is there an easy way to swap the Win and Alt keys in a script to emulate a Mac keyboard layout using a Windows keyboard layout?

**Comment by m2nlight** [comment]
Exchange # and !

**Comment by ElderDoge** [comment]
Thanks!

**Comment by m2nlight** [comment]
> Thanks!

Hi, I found a easy method to switch `win` and `alt`:

```ini
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Keyboard Layout]
"Scancode Map"=hex:00,00,00,00,00,00,00,00,05,00,00,00,5b,e0,38,00,38,00,5b,e0,\
  5c,e0,38,e0,38,e0,5c,e0,00,00,00,00

```

A GUI tool: [sharpkeys](https://github.com/randyrants/sharpkeys)
